### ISSUE TITLE
Sequence Labeling: Multi-Sentence Labeling

### ISSUE THREAD

**Issue by mariamanoli** [doccano/doccano#2174] opened 2023-04-12 22:11 UTC
System information
- OS Platform and Distribution -> Microsoft Windows 10 Home
- Python version -> Python 3.8.3  
-Project Sequence Labeling.

It allows me to label multiple words, under one label, when they are in the same row, but when those words are in different rows it doesn't let me.

**Comment by saeub** [comment] 2023-07-12 07:45
Duplicate of #1863.

**Closed** 2023-07-12 08:17 UTC
