### ISSUE TITLE
Upload Dataset Error 

### ISSUE THREAD

**Issue by Weber12321** [doccano/doccano#1780] opened 2022-04-13 08:57 UTC
### System information
- **OS Platform and Distribution**: Ubuntu 20.04 (WSL)
- **Python version**:  3.8.12
- **Docker version**: 20.10.7
- **Doccano version**: Latest

### Describe the problem
Hi I have tried to build the doccano via docker-compose in my WSL environment and it keeps remaining in progressing when I want to import dataset (no matter what format) and the logs shows up error as below. 
It seems that there is something wrong with uploading file to filepond. I am not so sure how to re config it with this problem.

I have tried to rebuild it in Windows environment and it shows the same error.

### Source code / logs
```
celery_1    | [2022-04-13 08:36:08,267: INFO/MainProcess] Task data_import.celery_tasks.import_dataset[2cc68d5e-c56d-49dc-b381-f6f9f9e6bdbf] received
celery_1    | [2022-04-13 08:36:08,305: ERROR/MainProcess] Task data_import.celery_tasks.import_dataset[2cc68d5e-c56d-49dc-b381-f6f9f9e6bdbf] raised unexpected: FileNotFoundError(2, 'No such file or direct
ory')
celery_1    | Traceback (most recent call last):
celery_1    |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
celery_1    |     R = retval = fun(*args, **kwargs)
celery_1    |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
celery_1    |     return self.run(*args, **kwargs)
celery_1    |   File "/backend/data_import/celery_tasks.py", line 55, in import_dataset
celery_1    |     upload_ids, errors = check_uploaded_files(upload_ids, file_format)
celery_1    |   File "/backend/data_import/celery_tasks.py", line 38, in check_uploaded_files
celery_1    |     if tu.file.size > settings.MAX_UPLOAD_SIZE:
celery_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/files.py", line 71, in size
celery_1    |     return self.storage.size(self.name)
celery_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 343, in size
celery_1    |     return os.path.getsize(self.path(name))
celery_1    |   File "/usr/local/lib/python3.8/genericpath.py", line 50, in getsize
celery_1    |     return os.stat(filename).st_size
celery_1    | FileNotFoundError: [Errno 2] No such file or directory: '/backend/filepond-temp-uploads/VU9qRP8j4MYFybEdKNFdcu/KBqfWzt9GFXVunj4GPeTnQ'

```
![image](https://user-images.githubusercontent.com/36941261/163137662-5a482df5-cbba-4cde-ac9c-2cc02f5c139e.png)

in filepond there is nothing in the temp directory:

**Comment by Hironsan** [comment] 2022-04-13 10:01
Thanks. I can reproduce the problem.

**Comment by Hironsan** [comment] 2022-04-13 10:32
OK. I understood the problem. The cause is https://github.com/doccano/doccano/pull/1779.

Before #1779, the temporary file was processed only in the backend container. After #1779, however, the file is processed in both the backend container and the celery container. So we need to create a volume and share the file across the containers. Without this, the file only exists in the backend container, that's why the error occurred.

Fixed in https://github.com/doccano/doccano/pull/1781

**Closed** 2022-04-13 10:34 UTC
Labels: bug

**Comment by Weber12321** [comment] 2022-04-14 06:38
Hi Hirosan, thank you for the fast fix. 
I have re-builded doccano today and it seems there is something wrong in `/process` with logs
![image](https://user-images.githubusercontent.com/36941261/163327778-3a5e4977-930c-4f5d-b94e-e46d7536416e.png)
when I attempt to upload `textLine`.

**Comment by Weber12321** [comment] 2022-04-14 07:26
Thank you for the fast fix, Hirosan, I have re-build it and it is fine now, many thanks!

**Comment by Hironsan** [comment] 2022-04-14 08:37
Your welcome.
