### ISSUE TITLE
Import conll2003 formatted text file

### ISSUE THREAD

**Issue by jdixosnd** [doccano/doccano#847] opened 2020-06-18 04:58 UTC
Firstly, I love this tool! It is super easy to deal with data. Thanks a ton for this amazing tool.
:)
Currently, Doccano supports 3 different types of formats that one can import. It would be great we can import (and export) in CONLL2003 format. (most of the model nowadays uses CONLL2003 as their input)

**Comment by kuraga** [comment] 2020-06-18 07:04
Duplicate of #650?

**Closed** 2020-07-11 01:33 UTC
Labels: enhancement
