### ISSUE TITLE
What happened to the UI feature to see the labels in 'Text classification' mode?

### ISSUE THREAD

**Issue by adaj** [doccano/doccano#1219] opened 2021-02-25 12:23 UTC
Hi there,

I have used Doccano before this new UI and I thought it was very handy to have the labels for text classification easy to see, but with the new UI one has to open the field of labels to select. It is still possible to have labels easy to see with some configuration or this feature was dropped? Below two prints to illustrate what I mean. 

![Screenshot_2](https://user-images.githubusercontent.com/13541251/109152796-43a51e00-776c-11eb-9a02-3138cb43efce.png)
![Screenshot_1](https://user-images.githubusercontent.com/13541251/109152800-443db480-776c-11eb-873f-fc2a0c3a6ad5.png)

**Comment by amanjain1397** [comment] 2021-02-25 21:15
Facing the same issue here.

**Comment by perjonasam** [comment] 2021-03-16 15:24
Me too. Very powerful to see the labels with the shortcuts when labeling tons of documents.

**Comment by cakiki** [comment] 2021-03-17 13:44
+1
Does anyone know if this is something that could easily be patched in Vue?

**Comment by Hironsan** [comment] 2021-03-22 12:30
![](https://i.gyazo.com/9a6153e294dad7785d5b0064001e3fc5.gif)

**Comment by kuraga** [comment] 2021-03-22 19:36
Duplicate of #635, #509, #627, #776, #991, #1035.

**Closed** 2021-03-22 23:39 UTC
Labels: enhancement
