### ISSUE TITLE
doccano didn't support long text Cross-line annotation？

### ISSUE THREAD

**Issue by cqray1990** [doccano/doccano#2219] opened 2023-06-14 03:29 UTC
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:ubantu os
*   Python Version Used: pyhthon3.8
*   When you install doccano:doccano 1.8.3
*   How did you install doccano (Heroku button etc):

if my text assume like this:

generally speaking ,i am a hard working student especially do the thing i am interested in. i will try my best to finish it no matter how difficult it is. when i was sophomore, i found web design very interesting, so i learned 

i want to label 'try my best to finish it' , but the content is Cross-line annotation, it can't be selected， that's unreasonable

**Comment by saeub** [comment] 2023-07-12 07:45
Duplicate of #1863.

**Closed** 2023-07-12 08:17 UTC
