### ISSUE TITLE
Is there a way to change the order of labels that pop up during sequence labeling? The labels I'm using are in alphabetical and numerical order and it would be nice to be able to view them that way.

### ISSUE THREAD

**Issue by miriammikhelson** [doccano/doccano#1028] opened 2020-10-30 00:29 UTC
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by kuraga** [comment] 2020-10-30 12:46
Duplicate of #816.

**Closed** 2020-11-01 07:42 UTC
