### ISSUE TITLE
Export data will get nothing, if I choose only approved documents.

### ISSUE THREAD

**Issue by Ginnna** [doccano/doccano#1422] opened 2021-06-21 06:39 UTC
if I choose only approved documents, the zip file contains nothing

if I don't choose it, the zip file contains "all.json".

But those txt I have checked.

**Comment by luoy2** [comment] 2021-07-27 02:20
same here, sequence labeling project

**Comment by colinux** [comment] 2021-08-13 09:13
I'm new in Doccano and had this issue too.

I found since https://github.com/doccano/doccano/pull/1402/ the "check" button toggle documents as "confirmed", it doesn't approve them anymore. So in database, the approver id remains empty, and there are no document to export,. I didn't find any way to approve document anymore, this is sort of disconnected from the frontend.

I'm not sure what direction the new workflow with document state related in discussions is taking. Do we need another "approve" button in addition to the "complete" button ? Or can it be done in one step ? Or maybe a new export setting to allow confirmed documents export ?

**Comment by shensmobile** [comment] 2021-08-16 19:28
Is confirmed used for anything aside from filtering?  If so, they should probably just be merged into one status/flag.

**Comment by daleevans** [comment] 2021-08-17 00:03
i've just run into this issue myself, i worked around with this minor change to sync the approved_by_user with the example state:

```
diff --git a/backend/api/views/example_state.py b/backend/api/views/example_state.py
index 38a82217..57ea018d 100644
--- a/backend/api/views/example_state.py
+++ b/backend/api/views/example_state.py
@@ -1,8 +1,9 @@
 from django.shortcuts import get_object_or_404
 from rest_framework import generics
 from rest_framework.permissions import IsAuthenticated
 
 from ..permissions import IsInProjectOrAdmin
 from ..serializers import ExampleStateSerializer
 
@@ -24,8 +25,42 @@ class ExampleStateList(generics.ListCreateAPIView):
 
     def perform_create(self, serializer):
         queryset = self.get_queryset()
+        example_id = self.kwargs['example_id']
+        example = Example.objects.get(pk=example_id)
+
         if queryset.exists():
+            example.annotations_approved_by = None
+            example.save()
             queryset.delete()
         else:
             example = get_object_or_404(Example, pk=self.kwargs['example_id'])
+            example.annotations_approved_by = self.request.user
+            example.save()
             serializer.save(example=example, confirmed_by=self.request.user)

```

**Comment by rjalexa** [comment] 2021-12-21 20:20
I also have the same problem. I have around 30% of the corpus annotated and checked but if I choose to export only the confirmed documents I only get a 22 byte all.json empty file. Running Doccano as installed by Docker Compose on an Apple M1 chip Mac.

**Comment by shensmobile** [comment] 2022-01-26 21:00
Has there been any progress on fixing this bug?  Or is there a way for us to manually edit the DB to convert "confirmed" to "approved"?

**Comment by mnschmit** [comment] 2022-03-14 09:18
@daleevans Can we use an adapted version of your code to auto-approve all documents marked as confirmed/done by a specific user?

It would also already be helpful to just get a list of all document ids that were marked as confirmed/done by a specific user. Then we could filter the all.json manually after exporting.

Does anyone know how to query the database to get such list?

**Comment by wpnbos** [comment] 2022-03-30 12:18
@mnschmit I ran into this problem and have written some code to extract all documents that were confirmed. Take a look:

`
client = ExtendedClient(DOCCANO_URL, USERNAME, PASSWORD)

# Get list of all example ids
ids = [example["id"] for example in client.get_examples(4, {"limit": [1200], "offset": [0]})["results"]]

# Query the database for the example states
example_states = [client.get_example_states(4, idx) for idx in ids]

# Filter the states based on if they were confirmed by the desired user and store the approved ids in a list
user_id = 1
confirmed_idx = [state["results"][0]["example"] for state in example_states if state["results"] and state["results"][0]["confirmed_by"] == user_id]
`

`confirmed_idx` then is a list of example ids approved by the specified user

**Comment by mnschmit** [comment] 2022-03-31 11:01
@wpnbos Thank you for sharing that approach! I didn't know about the doccano client!

**Closed** 2022-04-15 04:03 UTC
Labels: bug, enhancement

**Comment by flatplate** [comment] 2022-04-20 20:50
To add to @wpnbos solution, parameter `4` in `client.get_examples` is the project id, you can find it by running `client.get_project_list()`.

Also, you can directly install the repo using `pip install git+https://github.com/doccano/doccano-client.git`
