### ISSUE TITLE
How to filter for sentances marked as Checked?

### ISSUE THREAD

**Issue by milos-cuculovic** [doccano/doccano#1060] opened 2020-11-20 08:02 UTC
Hi, I am using doccano since a few days now where some colleagues are annotating the sentences and I mark them from non-checked to checked for the ones I judge good. 

Now, my question is how to filter for checked ones only? The Done / Undone filter only shows sentences in sequence labeling that have at least one annotation / no annotation. Is there such a filter? If not, what is then the purpose of checked / non checked? If no such a filtering feature, can I do the query through the DB? If yes, how?

Thank you in advance. I really appreciate your work on doccano, a great tool.

*   Operating System: Ubuntu 20.04 LTS
*   Python Version Used: Python 3.8.5
*   When you install doccano: Last week
*   How did you install doccano (Heroku button etc): Docker

**Comment by kuraga** [comment] 2020-11-20 10:24
Duplicate of #725 (merged to #505, has been merged to #280)?

**Comment by milos-cuculovic** [comment] 2020-11-20 11:32
Thank you @kuraga ! The second part of the question, can we filter in a different way, directly in the DB for example?

**Closed** 2021-03-23 03:00 UTC
Labels: question
